### ISSUE TITLE
Get PAT button postion

### ISSUE THREAD

**Issue by jofster** [Bit-Nation/bit-nation.github.io-old#14]
If this was moved to the right (under the text) the total height of this section would be reduced and eliminate some of the large empty space currently under the text

**Comment by ETeissonniere** [comment]
I prefer to keep it as it is, it feels better

**Comment by ETeissonniere** [comment]
However, I will reduce the margin at the top of the button

**Comment by ETeissonniere** [comment]
Closing via  5a7c26e
