### ISSUE TITLE
Stylesheet suggestion - light grey

### ISSUE THREAD

**Issue by jofster** [Bit-Nation/bit-nation.github.io-old#19]
Perhaps lighten it slightly to e.g. #BBBBBB to improve legibility while still retaining the white/grey combination

**Comment by ETeissonniere** [comment]
@jofster for which parts of the website? Can you explain a bit please?

**Comment by jofster** [comment]
for the ICO homepage - the "body" copy is in a grey around which there were some comments about legibility over the map background images. If the grey is lightened it could resolve this

**Comment by ETeissonniere** [comment]
Yeah we fixed that by changing a few things :wink:, we now have ways better backgrounds!
