### ISSUE TITLE
NASDAQ logo

### ISSUE THREAD

**Issue by xsttx** [Bit-Nation/bit-nation.github.io-old#5]
Make NASDAQ logo white. Add more media references?

**Comment by xsttx** [comment]
Actually, forget it, let's make all media logos 41B6E6 as well, it will provide more balance.

**Comment by ETeissonniere** [comment]
I think it is better to keep it white, it feels better, thoughts @xsttx ?

**Comment by ETeissonniere** [comment]
Closing via b038ef5
