### ISSUE TITLE
Consistent Main Menu

### ISSUE THREAD

**Issue by camilolunacom** [Bit-Nation/bit-nation.github.io-old#65]
The current main menu has a link to a section on the main page, a link to the Whitepaper and links to other pages from the website. 

It would be better to have a Main Menu with links that point only to other pages from the website so it can be replicated on all other pages.

Ex: Home Documents Events Announcements

And make a general page for each, with the most relevant info on top ie. Documents > Whitepaper; Events > Dipcon; Announcements > TSE Announcement.

This way we can maintain the main menu consistent in all pages and avoid changing it frequently.

**Comment by xsttx** [comment]
I agree.
