### ISSUE TITLE
Add "borders"

### ISSUE THREAD

**Issue by xsttx** [Bit-Nation/bit-nation.github.io-old#7]
Add very very thin lines to separate/ frame the sections (in white for the bright blue sections, and in bright blue for all other sections). @DeveloppSoft

**Comment by ETeissonniere** [comment]
I don't think this is necessary, the sections are already "separated" thanks to the different backgrounds, IMO it would be too much

**Comment by xsttx** [comment]
I think just very thin discreet lines would make it look more "polished"

**Comment by ETeissonniere** [comment]
Will check

**Comment by ETeissonniere** [comment]
Borders aren't easily seen, after some tries it appears to be either useless of ugly
